FROM almalinux:9
#CMD [ "ping","google.com" ]
#ENTRYPOINT [ "ping","google.com" ]

CMD [ "google.com" ]
ENTRYPOINT [ "ping" ]


# docker build -t entrypoint:v1 .
# docker run -d entrypoint:v1  yahoo.com
# docker exec -it <container_id> bash
